[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/scrape"
  to   = "/.netlify/functions/scrape-background"
  status = 200

[[redirects]]
  from = "/api/cruises"
  to   = "/.netlify/functions/cruises"
  status = 200
